/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

/**
 *
 * @author HP001
 */
public class page4 extends HttpServlet {
private static final long serialVersionUID = 1L;
    public page4(){
    super();
    //todo Autogenerated constructor stub
    } 

public  void doget( HttpServletRequest request,HttpServletResponse response) throws  ServletException,IOException{
    response.getWriter().append("Served at:").append(request.getContextPath());
} 

public void dopost(HttpServletRequest request,HttpServletResponse response) throws  ServletException,IOException{
HttpSession session= request.getSession();  
session.setAttribute("Mentor Phone", request.getParameter("mentor_phone")); 
session.setAttribute("file_path_name", request.getParameter("file_path_name")); 
session.setAttribute("Percentage", request.getParameter("percentage")); 
session.setAttribute("grade", request.getParameter("Grade")); 
session.setAttribute("score", request.getParameter("score")); 

RequestDispatcher rd=request.getRequestDispatcher("Form4.jsp");
rd.forward(request, response);

}
   

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}
